---
title: "Evaluating tree distance metrics with method of Lin et al. 2012"
author: "Martin R. Smith"
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2:
    includes:
      in_header: ../inst/preamble.tex
  rmarkdown::html_document:
bibliography: ../inst/REFERENCES.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa-old-doi-prefix.csl

vignette: >
  %\VignetteIndexEntry{Lin et al. 2012's Tree distance metric evaluation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The efficacy of clustering relies on the dissimilarity
measure used. We conducted two preliminary tests on RF
and matching metrics as dissimilarity measures in clustering. In each test, we generate 1,000 data sets, each of
200 random binary trees. 
In the first test, the trees in each
data set are generated by a two-step process. 
We first sample two binary trees on k leaves (k < 100) and use them
as two different skeletons. 

Then, from each of the two
skeletons, a set of 100 [!?] trees is generated by adding the rest
of the (n - k) leaves one by one. 

To add a new leaf, an edge
in the current tree is selected uniformly at random and the
new leaf is attached to that edge. We vary k from 40 to
90

```{r, echo=FALSE, message=FALSE, cache=TRUE}


```

In the second test, we begin with two randomly
chosen trees on n < 100 leaves. Each tree in a data set is
generated by performing k LLI operations on one of these
trees. 100 such trees are generated from each of the two
initial trees. We vary k from 10ð0:1nÞ to 40ð0:4nÞ. The
200 trees in each data set are given as input to the clustering
algorithm to check if the algorithm can distinguish the trees
in the two clusters—where trees generated from the same
skeleton are considered to be in the same cluster.

```{r, echo=FALSE, message=FALSE, cache=TRUE}


```

We apply a standard hierarchical clustering approach to
the pairwise distance matrices generated by RF and
matching distances. The similarity between clusters C1
and C2 is measured by the following three linkage criteria:
1. Complete linkage: maxfDða; bÞja 2 C1; b 2 C2g.
2. Single linkage: minfDða; bÞja 2 C1; b 2 C2g.
3. Average linkage: 1
jC1kC2j
P
a2C1;b2C2 Dða; bÞ.
A run of the algorithm on a particular data set is
considered to err if it is unable to place every tree generated
from the same skeleton in one cluster. We present, in
Table 1, the error rates obtained from 1,000 such data sets
for each parameter in the first test. For values of k higher
than 0:7n both distance measures perform equally well, but,
as expected, the matching distance has significantly better
performance over a large range of input parameters. Table 2
shows the error rates in the second test. Once again, the
matching distance performs significantly better than RF
distance.
