---
title: "3.1.4, 3.1.5: Saturation and sensitivity"
output:
  rmarkdown::html_vignette:
    default: yes
vignette: >
  %\VignetteIndexEntry{3.1.4, 3.1.5: Saturation and sensitivity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE, message=FALSE}
library('Quartet', exclude = 'RobinsonFoulds')
library('TreeTools', quietly = TRUE, warn.conflicts = FALSE)
library('TreeDist')
library('TreeDistData')
data('pectinateDistances11', package = 'TreeDistData')
pd11 <- pectinateDistances11
pd11[c('mast', 'masti'), ] <- -pd11[c('mast', 'masti'), ]
GetData <- function (distances) {
  c(
    atMax = sum(abs(distances - max(distances)) < .Machine$double.eps^0.5),
    #nearMax = sum(abs(distances - max(distances)) < max(distances) * 0.001),
    #floatUniqueScores = length(unique(distances)),
    uniqueScores = length(unique(round(distances, -log10(.Machine$double.eps^0.5))))
  )
}
```

Number of 100&nbsp;000 trees at maximum distance from a pectinate 11-leaf
reference tree:

```{r kable, echo=FALSE}
dat <- apply(pd11, 1, GetData)
colnames(dat) <- tdMdAbbrevs[colnames(dat)]
rownames(dat) <- c('Trees with maximum score', 'Unique distances')
.TDDTable(DT::datatable, t(dat))
```
