---
title: "Heterogeneity"
author: "Martin R. Smith"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
bibliography: ../inst/REFERENCES.bib
csl: ../inst/apa-old-doi-prefix.csl
vignette: >
  %\VignetteIndexEntry{Heterogeneity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{R initialize, echo=FALSE}
library('TreeDistData')
data('bullseyeDistances', package = 'TreeDistData')
data('bullseyeMorphScores', package = 'TreeDistData')
methods <- tdMethods[!tdMethods %in% c('mafi', 'nni_t')]

dists20 <- bullseyeDistances$`20 leaves`
dists50 <- bullseyeDistances$`50 leaves`

# Convert from similarity to distance
dists20[['mast']] <- dists20[['mast']][1, 1] - dists20[['mast']]
dists20[['masti']] <- dists20[['masti']][1, 1] - dists20[['masti']]

dists50[['mast']] <- dists50[['mast']][1, 1] - dists50[['mast']]
dists50[['masti']] <- dists50[['masti']][1, 1] - dists50[['masti']]

PlotMDS <- function(method, points) {
  pts <- points[[method]]
  plot(pts, pch = 20, cex = 0.3, xlab = '', ylab = '', axes = FALSE,
       col = TreeDistCol(method))

  z <- MASS::kde2d(pts[, 1], pts[, 2])
  contour(z, add = TRUE, col = TreeDistCol(method, '88'))
}

PlotText <- function (text, rotate = FALSE) {
  plot(0, 0, type='n', axes = FALSE)
  text(0, 0, text, srt = if (rotate) 90 else 0)
}

BallVol <- function (r, n) {
  r^n * pi^(n / 2) / gamma((n / 2) + 1)
}

```

20-leaf trees, K

```{r K-ring-20, echo=FALSE, fig.width=8, fig.asp=4/5}
PlotK <- function (method) {
  dists <- as.matrix(dists20[[method]])
  nBin <- 40
  r <- if (length(unique(as.numeric(dists))) < nBin) {
    sort(unique(as.numeric(dists)))
  } else {
    seq(0, max(dists), length.out = nBin + 1L)[-1]
  }
  k12r <- apply(dists, 1, function (d) {
    vapply(r, function (bin) {
      sum(d < bin)
    }, 1)
  }) - 1L
  
  plot(as.double(k12r) ~ rep(r, ncol(k12r)), col = TreeDistCol(method), axes = FALSE,
       ylim=c(min(0, k12r), max(0, k12r)), pch = '.')
  #l12r <- (k12r * (3/4) / pi)^1/3 - r
  lapply(c(2, 3, 4, 6, 8, 10, 12, 15, 20, 40), function (n) {
    lines(r, BallVol(r, n) / max(BallVol(r, n)) * ncol(dists), 
          col = '#aaaaaa77')
  })
  points(rowMeans(k12r) ~ r, col = TreeDistCol(method))

  
  abline(h = 0, col = TreeDistCol(method))
  legend('topleft', tdAbbrevs[method], bty = 'n')
}
par(mfrow=c(4, 5), mar = rep(1, 4))
lapply(methods, PlotK) -> XX
```

50-leaf trees, K
```{r K-ring-50, echo=FALSE, fig.width=8, fig.asp=4/5}
PlotK <- function (method) {
  dists <- as.matrix(dists50[[method]])
  nBin <- 40
  r <- if (length(unique(as.numeric(dists))) < nBin) {
    sort(unique(as.numeric(dists)))
  } else {
    seq(0, max(dists), length.out = nBin + 1L)[-1]
  }
  k12r <- apply(dists, 1, function (d) {
    vapply(r, function (bin) {
      sum(d < bin)
    }, 1)
  }) - 1L
  
  plot(as.double(k12r) ~ rep(r, ncol(k12r)), col = TreeDistCol(method), axes = FALSE,
       ylim=c(min(0, k12r), max(0, k12r)), pch = '.')
  #l12r <- (k12r * (3/4) / pi)^1/3 - r
  lapply(c(2, 3, 4, 6, 8, 10, 12, 15, 20, 40), function (n) {
    lines(r, BallVol(r, n) / max(BallVol(r, n)) * ncol(dists), 
          col = '#aaaaaa77')
  })
  points(rowMeans(k12r) ~ r, col = TreeDistCol(method))

  
  abline(h = 0, col = TreeDistCol(method))
  legend('topleft', tdAbbrevs[method], bty = 'n')
}
par(mfrow=c(4, 5), mar = rep(1, 4))
lapply(methods, PlotK) -> XX
```

20-leaf trees, O

```{r O-ring, echo=FALSE, fig.width=8, fig.asp=4/5}
PlotO <- function (method) {
  dists <- as.matrix(dists20[[method]])
  nBin <- 40
  r <- if (length(unique(as.numeric(dists))) < nBin) {
    sort(unique(as.numeric(dists)))
  } else {
    seq(0, max(dists), length.out = nBin + 1L)[-1]
  }
  k12r <- apply(dists, 1, function (d) {
    vapply(r, function (bin) {
      sum(d < bin)
    }, 1)
  }) - 1L
  
  o12r <- k12r[-1, ] - k12r[-nrow(k12r), ]
  
  plot(as.double(o12r) ~ rep(r[-1], ncol(o12r)), col = TreeDistCol(method), axes = FALSE,
       ylim=c(min(0, o12r), max(0, o12r)), pch = '.')
  
  lapply(c(2, 3, 4, 6, 8, 10, 12, 15, 20, 40), function (n) {
    shellVol <- BallVol(r[-1], n) - BallVol(r[-length(r)], n)
    lines(r[-1], shellVol / max(shellVol) * ncol(dists), 
          col = '#aaaaaa77')
  })
  points(rowMeans(o12r) ~ r[-1], col = TreeDistCol(method))

  abline(h = 0, col = TreeDistCol(method))
  legend('topleft', tdAbbrevs[method], bty = 'n')
}
par(mfrow=c(4, 5), mar = rep(1, 4))
lapply(methods, PlotO) -> XX
```

```{R scaling, echo=FALSE}
metricPts20 <- lapply(dists20[methods], cmdscale, k = 2L)
metricPts50 <- lapply(dists50[methods], cmdscale, k = 2L)
NMP <- function (td) MASS::isoMDS(td, k = 2, trace = FALSE)$points
nonMetricPts20 <- lapply(dists20[methods], NMP)
nonMetricPts50 <- lapply(dists50[methods], NMP)
```

```{R do-plot, echo=FALSE, fig.asp=34/41, fig.width = 10}
nMethods <- length(methods)
layoutMat <- matrix(0, nrow = 10, ncol = 1L + (nMethods / 2))
layoutMat[1, ] <- 0:10
layoutMat[6, 2:11] <- 11:20
layoutMat[2:5, 1] <- 21:24
layoutMat[2:5 + 5, 1] <- 25:28
layoutMat[c(2, 7, 3, 8, 4, 9, 5, 10), -1] <- 
  matrix(29:108, nrow = 8, ncol = nMethods / 2, byrow = TRUE)

layout(layoutMat,
       height = rep(c(1, rep(4, 4)), 2), 
       width = c(1, rep(4, nMethods / 2)))
par(oma = c(0, 0, 0, 0), xpd = TRUE, mar = rep(0.2, 4L), cex = 0.8)

lapply(methods, function (method) PlotText(tdAbbrevs[method])) -> XX

PlotText('20 leaves, metric', rotate = TRUE)
PlotText('20 leaves, metric', rotate = TRUE)
PlotText('20 tips, non-metric', rotate = TRUE)
PlotText('20 tips, non-metric', rotate = TRUE)
PlotText('50 tips, metric', rotate = TRUE)
PlotText('50 tips, metric', rotate = TRUE)
PlotText('50 tips, non-metric', rotate = TRUE)
PlotText('50 tips, non-metric', rotate = TRUE)


lapply(methods, PlotMDS, metricPts20) -> XX

lapply(methods, PlotMDS, nonMetricPts20) -> XX

lapply(methods, PlotMDS, metricPts50) -> XX

lapply(methods, PlotMDS, nonMetricPts50) -> XX
```
