---
title: "Accounting for tree shape"
author: "Martin R. Smith <martin.smith@durham.ac.uk>"
date: "`r Sys.Date()`"
output: 
  bookdown::pdf_document2:
    toc: no
  html_document:
    default: yes
---

```{r define-parameters, echo = FALSE}
require('TreeTools')
require('TreeDist')
require('TreeDistData')
nSample <- 100L
```

```{r init, echo = FALSE}
ShapeEffect <- function (nTip, nSample) {

  .CalcShapeEffect <- function (Func) {
    message('...')
    dists <- as.matrix(Func(trees))
    ShapeDists <- function (i, j) {
      d <- dists[shapeNumbers == i, shapeNumbers == j]
      d[upper.tri(d, diag = (i != j))]
    }
    go <- matrix(seq_len(nShapes) - 1L, nShapes, nShapes)
    x <- t(go)[lower.tri(go, diag = TRUE)]
    y <- go[lower.tri(go, diag = TRUE)]
    ret <- mapply(ShapeDists, x, y)
  }

  tipLabels <- paste0('t', seq_len(nTip))
  nShapes <- NUnrootedShapes(nTip)
  shapeKeys <- UnrootedKeys(nTip)
  shapes <- lapply(shapeKeys, UnrootedTreeWithKey, nTip = nTip)
  trees <- structure(unlist(lapply(shapes, function(skeleton) {
    unique(lapply(rep(0, nSample * 1.1), function(xx) {
      skeleton$tip.label <- sample(tipLabels)
      skeleton
    }))[seq_len(nSample)]
  }), recursive = FALSE), class = 'multiPhylo')

  shapeNumbers <- rep(seq_along(shapeKeys) - 1L, each = nSample)
  lapply(TreeDistData::TDFunctions, .CalcShapeEffect)
}


PlotMethod <- function (method, doPlot = TRUE) {
  methodEffect <- se[[method]]
  dat <- data.frame(
    shapePair = rep(as.factor(seq_along(methodEffect)),
                    sapply(methodEffect, length)),
    distance = unlist(methodEffect))
  reg <- summary(lm(distance ~ shapePair, data = dat))

  if (doPlot) {
    plot(type='n', 0, 0, xlim = c(-1, 1), ylim = c(-1, 1), axes = F)
    text(0, 0.5, abbrevs[method], col = TreeDistCol(method))
    text(0, -0.5, signif(reg$adj.r.squared, 3))

    plot(dat, border = TreeDistCol(method), axes = FALSE)
  }
  reg$adj.r.squared
}
```

```{r generate-data, echo = FALSE}
se <- ShapeEffect(8, nSample)
seMethods <- names(se)
nMethod <- length(seMethods)
```

```{r analyse, echo = FALSE}
par(xpd = NA)
r2 <- vapply(seMethods, PlotMethod, doPlot = FALSE, double(1))
plot(log10(r2), ylab='', xlab='', axes = FALSE, pch = 3, ylim=c(-9, 0))
text(seq_along(seMethods), log10(r2), paste(round(r2 * 100, 1), '%'),
      col = TreeDistCol(seMethods), pos = 4, srt = 90)
text(srt = 90, seq_along(seMethods), -7, TreeDistData::tdAbbrevs[seMethods], 
     col = TreeDistCol(seMethods), pos = 2)
axis(2)
mtext(expression('log'[10]*'(r'^2*')'), 2, 2.5)
```

```{r text-table, output = 'asis', echo= FALSE}
result <- t(signif(vapply(seMethods, PlotMethod, doPlot = FALSE, double(1)), 3))
plot(log(result))
colnames(result) <- TreeDistData::tdAbbrevs[colnames(result)]
knitr::kable(result)
```

```{r plot, echo = FALSE}
cbPalette8 <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", 
"#D55E00", "#CC79A7")
header <- cbind(c(1, 1), matrix(2:21, ncol=10, byrow=TRUE))
body <- matrix(rep(21 + seq_len(nMethod * 2), rep(c(1, 10), nMethod)),
               byrow=TRUE, ncol = 11)
layout(rbind(header, body), widths = c(2, rep(1, 10)))
par(mar = rep(0, 4L))

plot(type='n', 0, 0, xlim = c(-1, 1), ylim = c(-1, 1), axes = F)
text(0, 0.8, 'p(same)')

palette <- c( colorspace::sequential_hcl(8, h = 0, c = 0, l = c(10, 95),
                                         power = 0.9)[3:8], '#FFFFFF')
alongPal <- seq_along(palette)
nPal <- length(palette)

xMid <- c(-0.7, 0, 0.7)
xWid <- 0.15
rect(xMid - xWid, 0.4, xMid + xWid, 0.2, col = palette[6:4])
text(xMid, 0.2, pos = 1, labels = c('p \u2264 1', '\u2264 0.1', '0.05'))
rect(xMid - xWid, -0.2, xMid + xWid, -0.4, col = palette[3:1])
text(xMid, -0.4, pos = 1, labels = c('0.01', '0.001', '0.0001'))

shape1 <- c(0,0,0,0, 1,1,1, 2,2, 3)
shape2 <- c(0,1,2,3, 1,2,3, 2,3, 3)

xx <- lapply(c(shape1, shape2), function (shape) {
  plot(UnrootedTreeWithShape(shape, nTip = 8),
       edge.color = cbPalette8[shape + 1L])
  text(1, 9, shape + 1L, col = cbPalette8[shape + 1L])
})

lapply(seMethods, PlotMethod) -> XX
```

