---
title: "Heterogeneity"
output: 
  bookdown::pdf_document2:
    toc: no
  rmarkdown::html_vignette:
    default: yes
bibliography: ../inst/REFERENCES.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa-old-doi-prefix.csl
vignette: >
  %\VignetteIndexEntry{Heterogeneity}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{R initialize, echo=FALSE, message=FALSE}
library('TreeDistData')
library('spatstat')
data('bullseyeDistances', package = 'TreeDistData')
data('bullseyeMorphScores', package = 'TreeDistData')
methods <- tdMethods[!tdMethods %in% c('mafi', 'nni_t')]

dists20 <- bullseyeDistances$`20 leaves`
dists50 <- bullseyeDistances$`50 leaves`

# Convert from similarity to distance
dists20[['mast']] <- dists20[['mast']][1, 1] - dists20[['mast']]
dists20[['masti']] <- dists20[['masti']][1, 1] - dists20[['masti']]

dists50[['mast']] <- dists50[['mast']][1, 1] - dists50[['mast']]
dists50[['masti']] <- dists50[['masti']][1, 1] - dists50[['masti']]

PlotMDS <- function(method, points) {
  pts <- points[[method]]
  plot(pts, pch = 20, cex = 0.3, xlab = '', ylab = '', axes = FALSE,
       col = TreeDistCol(method))
  
  z <- MASS::kde2d(pts[, 1], pts[, 2])
  contour(z, add = TRUE, col = TreeDistCol(method, '88'))
}

PlotText <- function (text, rotate = FALSE) {
  plot(0, 0, type='n', axes = FALSE)
  text(0, 0, text, srt = if (rotate) 90 else 0)
}

BallVol <- function (r, n) {
  pmax(0, r)^n * pi^(n / 2) / gamma((n / 2) + 1)
}

```

## Spatial statistics

20-leaf trees, K function [@Wiegand2004]


```{r K-fn-20, echo=FALSE, fig.width=8, fig.asp=4/5}
PlotK <- function (method) {
  dists <- as.matrix(dists20[[method]])
  nBin <- 40
  r <- if (length(unique(as.numeric(dists))) < nBin) {
    sort(unique(as.numeric(dists)))
  } else {
    seq(0, max(dists), length.out = nBin + 1L)[-1]
  }
  k12r <- apply(dists, 1, function (d) {
    vapply(r, function (bin) {
      sum(d < bin)
    }, 1)
  }) - 1L
  
  plot(as.double(k12r) ~ rep(r, ncol(k12r)), col = TreeDistCol(method), axes = FALSE,
       ylim=c(min(0, k12r), max(0, k12r)), pch = '.')
  points(rowMeans(k12r) ~ r, col = TreeDistCol(method))
  
  model <- NULL
  try(model <- nls(as.double(k12r) ~ BallVol(rep(r, ncol(k12r)), n) * k,
               start = list(n = 12, k = 1000)), silent = TRUE)
  if (!is.null(model)) {
    lines(sort(rep(r, ncol(k12r))), sort(predict(model)), col=TreeDistCol(method, 'aa'))
  }
  
  abline(h = 0, col = TreeDistCol(method))
  legend('topleft', tdAbbrevs[method], bty = 'n')
}
par(mfrow=c(4, 5), mar = rep(1, 4))
lapply(methods, PlotK) -> XX
```

20-leaf trees, O ring [@Wiegand2004]

```{r O-ring-20, echo=FALSE, fig.width=8, fig.asp=4/5}
PlotO <- function (method) {
  dists <- as.matrix(dists20[[method]])
  nBin <- 40
  r <- if (length(unique(as.numeric(dists))) < nBin) {
    sort(unique(as.numeric(dists)))
  } else {
    seq(0, max(dists), length.out = nBin + 1L)[-1]
  }
  k12r <- apply(dists, 1, function (d) {
    vapply(r, function (bin) {
      sum(d < bin)
    }, 1)
  }) - 1L
  
  o12r <- k12r[-1, ] - k12r[-nrow(k12r), ]
  
  plot(as.double(o12r) ~ rep(r[-1], ncol(o12r)), col = TreeDistCol(method), axes = FALSE,
       ylim=c(min(0, o12r), max(0, o12r)), pch = '.')
  
  lapply(c(2, 3, 4, 6, 8, 10, 12, 15, 20, 40), function (n) {
    shellVol <- BallVol(r[-1], n) - BallVol(r[-length(r)], n)
    lines(r[-1], shellVol / max(shellVol) * ncol(dists), 
          col = '#aaaaaa77')
  })
  points(rowMeans(o12r) ~ r[-1], col = TreeDistCol(method))

  abline(h = 0, col = TreeDistCol(method))
  legend('topleft', tdAbbrevs[method], bty = 'n')
}
par(mfrow=c(4, 5), mar = rep(1, 4))
lapply(methods, PlotO) -> XX
```

## Multi-dimensional scaling

```{R scaling, echo=FALSE}
metricPts20 <- lapply(dists20[methods], cmdscale, k = 2L)
metricPts50 <- lapply(dists50[methods], cmdscale, k = 2L)
NMP <- function (td) MASS::isoMDS(td, k = 2, trace = FALSE)$points
nonMetricPts20 <- lapply(dists20[methods], NMP)
nonMetricPts50 <- lapply(dists50[methods], NMP)
```

```{R do-plot, echo=FALSE, fig.asp=34/41, fig.width = 10}
nMethods <- length(methods)
layoutMat <- matrix(0, nrow = 10, ncol = 1L + (nMethods / 2))
layoutMat[1, ] <- 0:10
layoutMat[6, 2:11] <- 11:20
layoutMat[2:5, 1] <- 21:24
layoutMat[2:5 + 5, 1] <- 25:28
layoutMat[c(2, 7, 3, 8, 4, 9, 5, 10), -1] <- 
  matrix(29:108, nrow = 8, ncol = nMethods / 2, byrow = TRUE)

layout(layoutMat,
       height = rep(c(1, rep(4, 4)), 2), 
       width = c(1, rep(4, nMethods / 2)))
par(oma = c(0, 0, 0, 0), xpd = TRUE, mar = rep(0.2, 4L), cex = 0.8)

lapply(methods, function (method) PlotText(tdAbbrevs[method])) -> XX

PlotText('20 leaves, metric', rotate = TRUE)
PlotText('20 leaves, metric', rotate = TRUE)
PlotText('20 tips, non-metric', rotate = TRUE)
PlotText('20 tips, non-metric', rotate = TRUE)
PlotText('50 tips, metric', rotate = TRUE)
PlotText('50 tips, metric', rotate = TRUE)
PlotText('50 tips, non-metric', rotate = TRUE)
PlotText('50 tips, non-metric', rotate = TRUE)


lapply(methods, PlotMDS, metricPts20) -> XX

lapply(methods, PlotMDS, nonMetricPts20) -> XX

lapply(methods, PlotMDS, metricPts50) -> XX

lapply(methods, PlotMDS, nonMetricPts50) -> XX
```

```{r k-estimates-2d, echo=FALSE}
par(mfrow=c(5, 4), mar = rep(0.2, 4))

PlotKest <- function(method, points) {
  pts <- points[[method]]
  colnames(pts) <- c('x', 'y')
  pppts <- as.ppp(pts, W= list(xrange = range(pts[, 1]), yrange = range(pts[, 2])))
  plot(Kest(pppts, correction = 'isotropic'), main = tdAbbrevs[method], 
       axes = FALSE)
}

lapply(methods, PlotKest, points = nonMetricPts20) -> XX
```

## O-ring analysis 

20 tips, metric and non-metric:

```{r o-ring-2d, echo=FALSE}
par(mfrow=c(8, 5), mar = rep(0.2, 4))

PlotOring <- function(method, points) {
  pts <- points[[method]]
  colnames(pts) <- c('x', 'y')
  pppts <- as.ppp(pts, W= list(xrange = range(pts[, 1]), yrange = range(pts[, 2])))
  
  #g <- spatstat::pcf(pppts)
  g <- spatstat::pcfinhom(pppts)
  lambda <- summary(pppts)$intensity
  o <- spatstat::eval.fv(lambda * g)
  
  plot(o, main = tdAbbrevs[method], axes = FALSE, legend = FALSE)
}

lapply(methods, PlotOring, points = metricPts20) -> XX

lapply(methods, PlotOring, points = nonMetricPts20) -> XX
```

## Scaling analysis: fifty-leaf trees

Plots are essentially the same with fifty leaves:

50-leaf trees, K function  [@Wiegand2004]

```{r K-fn-50, echo=FALSE, fig.width=8, fig.asp=4/5}
PlotK <- function (method) {
  dists <- as.matrix(dists50[[method]])
  nBin <- 40
  r <- if (length(unique(as.numeric(dists))) < nBin) {
    sort(unique(as.numeric(dists)))
  } else {
    seq(0, max(dists), length.out = nBin + 1L)[-1]
  }
  k12r <- apply(dists, 1, function (d) {
    vapply(r, function (bin) {
      sum(d < bin)
    }, 1)
  }) - 1L
  
  plot(as.double(k12r) ~ rep(r, ncol(k12r)), col = TreeDistCol(method), axes = FALSE,
       ylim=c(min(0, k12r), max(0, k12r)), pch = '.')
  #l12r <- (k12r * (3/4) / pi)^1/3 - r
  lapply(c(2, 3, 4, 6, 8, 10, 12, 15, 20, 40), function (n) {
    lines(r, BallVol(r, n) * ncol(dists) / BallVol(max(r), n),
          col = '#aaaaaa77')
  })
  points(rowMeans(k12r) ~ r, col = TreeDistCol(method))

  
  abline(h = 0, col = TreeDistCol(method))
  legend('topleft', tdAbbrevs[method], bty = 'n')
}
par(mfrow=c(4, 5), mar = rep(1, 4))
lapply(methods, PlotK) -> XX
```

50-leaf trees, O ring [@Wiegand2004]

```{r O-ring-50, echo=FALSE, fig.width=8, fig.asp=4/5}
PlotO <- function (method) {
  dists <- as.matrix(dists50[[method]])
  nBin <- 40
  r <- if (length(unique(as.numeric(dists))) < nBin) {
    sort(unique(as.numeric(dists)))
  } else {
    seq(0, max(dists), length.out = nBin + 1L)[-1]
  }
  k12r <- apply(dists, 1, function (d) {
    vapply(r, function (bin) {
      sum(d < bin)
    }, 1)
  }) - 1L
  
  o12r <- k12r[-1, ] - k12r[-nrow(k12r), ]
  
  plot(as.double(o12r) ~ rep(r[-1], ncol(o12r)), col = TreeDistCol(method), axes = FALSE,
       ylim=c(min(0, o12r), max(0, o12r)), pch = '.')
  
  lapply(c(2, 3, 4, 6, 8, 10, 12, 15, 20, 40), function (n) {
    shellVol <- BallVol(r[-1], n) - BallVol(r[-length(r)], n)
    lines(r[-1], shellVol / max(shellVol) * ncol(dists), 
          col = '#aaaaaa77')
  })
  points(rowMeans(o12r) ~ r[-1], col = TreeDistCol(method))

  abline(h = 0, col = TreeDistCol(method))
  legend('topleft', tdAbbrevs[method], bty = 'n')
}
par(mfrow=c(4, 5), mar = rep(1, 4))
lapply(methods, PlotO) -> XX
```


## Reference
